### ISSUE TITLE
Error BeckerCommunicator thread not alive.

### ISSUE THREAD

**Issue by Dreaming-Codes** [RainerStaude/hass-becker-component-plus-pybecker#2]
```
Error executing script. Unexpected error for call_service at pos 1: Error BeckerCommunicator thread not alive.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 372, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 575, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/hass-becker-component-plus-pybecker/rf_device.py", line 72, in handle_pair
    await cls.becker.pair(f"{unit}:{channel}")
  File "/config/custom_components/hass-becker-component-plus-pybecker/pybecker/becker.py", line 218, in pair
    await self.send(channel, "TRAIN")
  File "/config/custom_components/hass-becker-component-plus-pybecker/pybecker/becker.py", line 160, in send
    await self.run_codes(ch, unit, cmd, test)
  File "/config/custom_components/hass-becker-component-plus-pybecker/pybecker/becker.py", line 145, in run_codes
    await self.write(codes)
  File "/config/custom_components/hass-becker-component-plus-pybecker/pybecker/becker.py", line 73, in write
    self.communicator.send(finalize_code(code))
  File "/config/custom_components/hass-becker-component-plus-pybecker/pybecker/becker_helper.py", line 272, in send
    raise BeckerConnectionError(
custom_components.hass-becker-component-plus-pybecker.pybecker.becker_helper.BeckerConnectionError: Error BeckerCommunicator thread not alive.
```

What am I doing wrong?

**Comment by Dreaming-Codes** [comment]
I forgot to plug in the USB stick
