### ISSUE TITLE
Becker USB Stick pairing doesnt work anymore / Home Assistant

### ISSUE THREAD

**Issue by weidianer** [RainerStaude/hass-becker-component-plus-pybecker#35]
Hello,

I have integrated the Centronic USB Stick with the Becker order number 4035 200 041 0 end of last year, that time I was able to pair the USB Stick. Last weekend I tried to open my shade sail with Home Assitant, but nothing happened. I only can control it with my becker remote control (SWC441-II). If I put on the training mode, I can hear the first clack. If I try to call the service for the USB stick with channel 2 and unit 2, nothing happens, no clack.

I turned on debug mode and according to this all looks fine:
2024-04-08 20:25:17.840 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel Soliday update ha-state now
2024-04-08 20:25:18.381 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel Soliday stopped at position 84
2024-04-08 20:25:18.381 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel Soliday update ha-state now
2024-04-08 20:25:18.388 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 2, command: HALT, argument: 0, packet: b'\x020000000002010B00A30000001737C0210102001010\x03'

so I cannot find any issues in my log file. But I am also not able to pair my USB Stick.

What I have done so far.
- complete reboot
- deleting all remotes (with 3 pushing time training botton)
- using the delopment2 branch
- using another USB slot

The USB stick is very close to the motor (5 Meters).

However, it worked Dec 2023 when I installed it and now nothing, dead - bit strange.

What else could be a thing to find out why I cannot pair the USB stick?

Thanks a lot - Oliver

**Comment by weidianer** [comment]
please find additional info from log file:

2024-04-08 20:46:59.621 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel Soliday stopped at position 79
2024-04-08 20:46:59.621 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel Soliday update ha-state now
2024-04-08 20:46:59.633 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 2, command: HALT, argument: 0, packet: b'\x020000000002010B00BF0000001737C02101020010F4\x03'
2024-04-08 20:47:25.036 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2024-04-08 20:47:25.037 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2024-04-08 20:47:25.040 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 2, command: TRAIN, argument: 0, packet: b'\x020000000002010B00C00000001737C0210102008083\x03'
2024-04-08 20:47:25.345 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 2, command: TRAIN, argument: 1, packet: b'\x020000000002010B00C10000001737C0210102008181\x03'
2024-04-08 20:47:25.652 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 2, command: RELEASE, argument: 0, packet: b'\x020000000002010B00C20000001737C0210102000001\x03'
2024-04-08 20:47:25.957 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 2, command: TRAIN, argument: 0, packet: b'\x020000000002010B00C30000001737C0210102008080\x03'
2024-04-08 20:47:26.261 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 2, command: TRAIN, argument: 1, packet: b'\x020000000002010B00C40000001737C021010200817E\x03'
2024-04-08 20:47:26.567 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 2, command: RELEASE, argument: 0, packet: b'\x020000000002010B00C50000001737C02101020000FE\x03'

**Comment by weidianer** [comment]
Hello, I installed it now on a new Raspi system - same here - no issues found in the log file but no way to pair the USB stick - but I cannot see an issue in log files. Is there  way to test the USB stick?

**Comment by RainerStaude** [comment]
Do you see any log messages, when you press any key on your remote?

**Comment by weidianer** [comment]
Hi, yes see below: pressing buttons on Home Assistant I can see these in the log:
2024-04-11 10:25:36.891 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737F, channel: 5, command: TRAIN, argument: 1, packet: b'\x020000000002010B00330000001737F02101050081DC\x03'
2024-04-11 10:25:36.991 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737F, channel: 5, command: RELEASE, argument: 0, packet: b'\x020000000002010B00340000001737F021010500005C\x03'
2024-04-11 10:25:37.093 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737F, channel: 5, command: TRAIN, argument: 1, packet: b'\x020000000002010B00350000001737F02101050081DA\x03'
2024-04-11 10:26:02.897 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel is travelling from position 50 to 100 in 0.0 seconds
2024-04-11 10:26:02.897 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel update ha-state now
2024-04-11 10:26:02.908 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737B, channel: 5, command: UP, argument: 0, packet: b'\x020000000002010B020D0000001737B02101050020A1\x03'
2024-04-11 10:26:04.004 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel is travelling from position 100 to 25 in 0.0 seconds
2024-04-11 10:26:04.004 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel update ha-state now
2024-04-11 10:26:04.016 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737B, channel: 5, command: UP, argument: 4, packet: b'\x020000000002010B020E0000001737B021010500249C\x03'
2024-04-11 10:26:05.061 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel is travelling from position 25 to 0 in 0.0 seconds
2024-04-11 10:26:05.062 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel update ha-state now
2024-04-11 10:26:05.070 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737B, channel: 5, command: DOWN, argument: 0, packet: b'\x020000000002010B020F0000001737B021010500407F\x03'


What I do not understand further is that in training the unit_id = 1737F and pressing buttons it shows 1737B....

And however, at pairing no click clack noise...just silence - I only hear the click if I am pressing the becker remote control (master).

Any idea how to find out what is wrong?

**Comment by weidianer** [comment]
I used the tool of Ole - and cannot find any error messages, see below pls:

./centronic-stick.py --send TRAIN --channel 1
Sending code 0000000002010B00000000001737B0210101008153 to device /dev/ttyACM0
Sending code 0000000002010B00010000001737B02101010000D3 to device /dev/ttyACM0
Sending code 0000000002010B00020000001737B0210101008151 to device /dev/ttyACM0

**Comment by RainerStaude** [comment]
The becker integration is also listening to any received packets from other remotes like your becker master remote. Do you see anything in the log files like this while pressing any keys on your master remote. If you have removed the USB stick recently, I would perform a reboot just to be sure before this test.
```
2024-04-10 07:32:17.282 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Received packet: unit_id: 12345, channel: 0, command: UP, argument: 0, packet: b'\x020000000002010B000000000012345029000000200B\x03'
```
The same is possible with `centronic-stick.py` and the option
`-l: listen on the centronic USB device to fetch the codes`

Do you receive anything?

What do you mean with unit_id = 1737F and pressing buttons it shows 1737B ?
Did you mix up channel and unit by mistake?

The becker.pair service needs to be filled with valid data like:
```
service: becker.pair
data:
  channel: 1
  unit: 1
```
You can get this view by selecting YAML modus and then FILL WITH EXAMPLE DATA

**Comment by RainerStaude** [comment]
Another thing. If the Motor was turned off for  a long time, it might be necessary to press stop about ten times ...

**Comment by RainerStaude** [comment]
Is it now working?

**Comment by weidianer** [comment]
Need to check once I am back from a weekend project. Will let u know. Thanks for asking.

**Comment by weidianer** [comment]
Hi 

Listen mode is showing nothing.

Still see all push bottoms in the log file

**Comment by weidianer** [comment]
Hi

I have a new stick now- same situation- so seems has nothing to do with the stick.

Any ideas?

**Comment by RainerStaude** [comment]
I had another chat with similar problems. The solution was to completely remove and add Becker again.
Temporarily remove Becker from config and delete the Becker custom components folder (can be done with HACS as well). Reboot and download Becker again. Perform another reboot and add Becker to the configuration.

After that you should verify if you see button presses from your master remote in the log.

Press halt 10 times in Home Assistant for each configured motor.

Verify that you did training with the right unit channel as mentioned in my previous comments.

Good luck...

**Comment by weidianer** [comment]
Strange as I tried it already on 2 different systems - one with a Rapsi and one with QNAP.

Just to make sure I understand:
1. Delete and re-install becker and remove all becker in configuration.yaml
2. reboot
3. download becker again via HACS and install it
4. reboot again
5. put becker information back into configuration.yaml

Questions:
- so I need to see master remote presses in HA log?
- what does the 10 times press halt?
- what do you mean the right unit? if I pair with channel 1 and unit 1 (I only have one remote master not sure what channel and unit it is) is there a relation between the remote master and the HA channel settings and unit settings? if so which? :-)

this is really bit crazy - I have now 2 USB sticks and 2 different machines .....

**Comment by weidianer** [comment]
another Question:

if you write REBOOT - do you mean full reboot or only HA restart.
Just asking as the QNAP needs 15 Minutes to reboot completely.

**Comment by weidianer** [comment]
New Update

If I am using in HA the pair service - I can see this here below:
2024-04-16 11:43:04.936 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2024-04-16 11:43:04.937 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2024-04-16 11:43:04.939 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 3, command: TRAIN, argument: 1, packet: b'\x020000000002010B00300000001737C0210103008111\x03'
2024-04-16 11:43:05.041 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 3, command: RELEASE, argument: 0, packet: b'\x020000000002010B00310000001737C0210103000091\x03'
2024-04-16 11:43:05.142 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737C, channel: 3, command: TRAIN, argument: 1, packet: b'\x020000000002010B00320000001737C021010300810F\x03'

SO - here I can see the unit_id: 1737C - BUT I cannot hear a click or clickclack

If I am pressing a button in HA of the HA integration, I can see below in the homeassistant.log:
2024-04-16 11:44:08.818 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737B, channel: 1, command: HALT, argument: 0, packet: b'\x020000000002010B031D0000001737B02101010010A4\x03'
2024-04-16 11:44:09.578 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel stopped at position 50
2024-04-16 11:44:09.578 DEBUG (MainThread) [custom_components.becker.cover] Sonnensegel update ha-state now
2024-04-16 11:44:09.590 DEBUG (Thread-3) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737B, channel: 1, command: HALT, argument: 0, packet: b'\x020000000002010B031E0000001737B02101010010A3\x03'

here I can see a different unit_id: 1737B

BUT: pressing a button, I only can see this from the HA UI, not for the physical remote control (master) in my homeassitant.log

Any idea?

**Comment by RainerStaude** [comment]
Hi,
which sunshade motor are you using?

**Comment by weidianer** [comment]
Hi,

the motor is a Becker L80-11-C12 Series.

Yes, this is true for both sticks, the old and the new one.

Yes I set the motor in pairing mode everytime before using the HA becker pair service.

I rebooted already several times :-)
No, I never saw the SWC441-II pressing button action in the HA log.

I did a blank install already with deleting centronic-stick.db it seems that there is no change.

Re the unit and channel - is it correct to use the first number of the unit-no? and I can use any channel from 1 to 5 this is up to me? I am asking as I only have this one motor to control!

Just to add this info, maybe relevant: I also have the Becker SensorControl SC811 which controls the Motor on Wind and Sun treshholds - does this maybe is anyhting to think of?

**Comment by weidianer** [comment]
this is my entry in the HA config file.

cover:
  - platform: becker
    device: "/dev/ttyACM0"
    filename: "centronic-stick.db" 
    covers:
      garten:
        friendly_name: "Sonnensegel Soliday"
        # Becker Centronic USB stick provides up to five units (1-5) with up to seven (1-7) channels
        # Unit 1 - Channel 2
        remote_id: "1737B:1"
        channel: "1:1"
        travelling_time_up: 30
        travelling_time_down: 26.5

**Comment by weidianer** [comment]
and this is what I see in the log after deleting the centronic-stick.db - so it is re-creating again:

WARNING (MainThread) [custom_components.becker.pybecker.becker] Unit 1 of Sonnensegel Soliday with channel 1:1 not registered in database file /config/centronic-stick.db!

**Comment by weidianer** [comment]
addition info. I had the motor 5 minutes without power - just to try if this helps - but I wasnt able to pair even with that action.

**Comment by weidianer** [comment]
Update: I also changed Battery on the becker remote - no progress.

**Comment by weidianer** [comment]
Update: I tried another USB port and nother USB cable - after that rebooted the Hardware - no affect - no click clack at pair service - logfile shows no issues.

**Comment by RainerStaude** [comment]
I updated the Becker integration for some other reasons. Please try latest version (even if I don't think that this will help). But it is worth to try.

**Comment by weidianer** [comment]
What version and when have you updated?

Is pyserial already part of your implementation? Could this be issue?

I do not understand that the pairing doesn't work. No click clack noise.

**Comment by RainerStaude** [comment]
Updated some minutes ago to version v0.3.4
Replaced some depreciated constants.

**Comment by RainerStaude** [comment]
Just saw in your config you are define remote id. But this is the id of the USB stick and not required 
   remote_id: "1737B:1"

This should be the remote id of you master remote (which you don't have as long as receiving is not working).

**Comment by weidianer** [comment]
I updated to v0.3.4
I removed "1737B:1"
I restarted HA
I started pair service after pressing 3 Sec on thge master remote (clack)
BUT still no pairing success.
How can I find out what the issues is? It is already the second USB.
Can there be an issues with the master remote?
This seems all to be very strange.

**Comment by RainerStaude** [comment]
Frustrating for me as well as you are not the only one with ithis similar issue.
Could you send pictures of your USB sticks (just for better documentation). Are both sticks looking like the same?
I'm not running out of ideas, but with just guessing it is difficult.
Could you send me a private message on LinkedIn (see my GitHub profile).

**Comment by weidianer** [comment]
Will do asap - talk soon.

**Comment by weidianer** [comment]
Just contacted you via LinkedIn.

Here are the 2 Sticks , red arrow means new one ![image](https://github.com/RainerStaude/hass-becker-component-plus-pybecker/assets/123209538/5c020634-8c21-44a7-842f-18b47e231474)

**Comment by dunimaniac** [comment]
Hello. My Integration also not working. The Stick ist visible in Hardware of HA. I Changed nothing in the Config but Entitits not aviable anymore.

LOG: 

2024-04-21 22:40:20.911 ERROR (MainThread) [homeassistant.components.cover] Error while setting up becker platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/becker/cover.py", line 100, in async_setup_platform
    PyBecker.setup(hass, device=device, filename=filename)
  File "/config/custom_components/becker/rf_device.py", line 58, in setup
    cls.becker = Becker(device_name=device, init_dummy=False, db_filename=filename, callback=callback)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/becker/pybecker/becker.py", line 58, in __init__
    self.communicator = BeckerCommunicator(device_name, callback)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/becker/pybecker/becker_helper.py", line 217, in __init__
    self._connection = BeckerConnection(device=device)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/becker/pybecker/becker_helper.py", line 99, in __init__
    self._device, self._is_serial = self._validate_device(device)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/becker/pybecker/becker_helper.py", line 179, in _validate_device
    raise BeckerConnectionError("{} is not existing".format(device))
custom_components.becker.pybecker.becker_helper.BeckerConnectionError: /dev/serial/by-id/usb-BECKER-ANTRIEBE_GmbH_CDC_RS232_v125_Centronic-if00 is not existing

**Comment by dunimaniac** [comment]
centronic stick db: 'utf-8' codec can't decode byte 0xa2 in position 99: invalid start byte

**Comment by KartonUlandar** [comment]
> centronic stick db: 'utf-8' codec can't decode byte 0xa2 in position 99: invalid start byte

Ive updated to 0.3.4 today and after my covers also not working anymore. The my-centronic-stick.db shows same error.
I rolled back with snapshot from Synology but it also stopped working with 0.3.3. 
I tried to pair again, but service becker.pair isnt avaiable.

Hope you can fix this issues. Worked so good before updating today.

**Comment by RainerStaude** [comment]
Centronic-Stick.db ist not a text file. Therefore it's not readable in file editor. This is OK and no problem.

**Comment by RainerStaude** [comment]
If Becker pair is not available, there's something went wrong with communication to USB stick.
Could you please check the log file and provide your config.
There's no need to re-pair your cover.

**Comment by RainerStaude** [comment]
@dunimaniac 
Looks like default path for the USB stick doesn't apply for your setup. Please check your correct device path and add it to your configuration. Please refer to the readme for more information.

**Comment by KartonUlandar** [comment]
Heres my config.yaml entry:
cover:
  - platform: becker
    device: "/dev/serial/by-id/usb-Becker-Antriebe_GmbH_CDC_RS232_v125_Centronic-if00"
    filename: "my-centronic-stick.db"
    covers:
      wohnzimmer:
        friendly_name: "Rollo Wohnzimmer"
        channel: "1"
        travelling_time_up: 21
        travelling_time_down: 18
      kuche:
        friendly_name: "Rollo Küche"
        channel: "2"
        travelling_time_up: 22
        travelling_time_down: 17
      abstellraum:
        friendly_name: "Rollo Abstellraum"
        channel: "3"
        travelling_time_up: 18
        travelling_time_down: 15

ID from USB Stick: /dev/serial/by-id/usb-Becker-Antriebe_GmbH_CDC_RS232_v125_Centronic-if00

Log shows 2 things on HA startup:

Logger: homeassistant.components.cover
Quelle: helpers/deprecation.py:206
Integration: Abdeckung (Dokumentation, Probleme)
Erstmals aufgetreten: 17:30:57 (12 Vorkommnisse)
Zuletzt protokolliert: 17:30:57

SUPPORT_CLOSE_TILT was used from becker, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE_TILT instead, please report it to the author of the 'becker' custom integration
SUPPORT_OPEN was used from becker, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please report it to the author of the 'becker' custom integration
SUPPORT_OPEN_TILT was used from becker, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN_TILT instead, please report it to the author of the 'becker' custom integration
SUPPORT_STOP was used from becker, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please report it to the author of the 'becker' custom integration
SUPPORT_SET_POSITION was used from becker, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please report it to the author of the 'becker' custom integration


Logger: homeassistant.config
Quelle: config.py:1324
Erstmals aufgetreten: 17:30:57 (1 Vorkommnisse)
Zuletzt protokolliert: 17:30:57

Invalid config for 'cover' from integration 'becker' at configuration.yaml, line 17: invalid slug küche (try kuche) for dictionary value 'covers', got {'wohnzimmer': {'friendly_name': 'Rollo Wohnzimmer', 'channel': '1', 'travelling_time_up': 21, 'travelling_time_down': 18}, 'küche': {'friendly_name': 'Rollo Küche', 'channel': '2', 'travelling_time_up': 22, 'travelling_time_down': 17}, 'abstellraum': {'friendly_name': 'Rollo Abstellraum', 'channel': '3', 'travelling_time_up': 18, 'travelling_time_down': 15}}

**Comment by RainerStaude** [comment]
@KartonUlandar 
The first issue is solved with new version v0.3.4
The second issue is due to wrong configuration. 
The configuration you posted doesn't fit to the error message (küche vs. kuche). Please check your configuration.
And don't forget to reboot afterwards.

**Comment by KartonUlandar** [comment]
Ah i changed it, but forgot to reload. Seems like its working again. Thanks for help :D

**Comment by dunimaniac** [comment]
Removed and Added Integration, try to pair but the shutter dont respond in learning mode with 2 Klacks.


2024-04-26 17:31:06.082 INFO (MainThread) [homeassistant.components.automation.dunstabzugshaube_aus] Dunstabzugshaube aus: Running automation actions
2024-04-26 17:31:06.082 INFO (MainThread) [homeassistant.components.automation.dunstabzugshaube_aus] Dunstabzugshaube aus: Executing step device automation
2024-04-26 17:31:37.766 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2024-04-26 17:31:37.766 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2024-04-26 17:31:37.772 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737D, channel: 2, command: TRAIN, argument: 1, packet: b'\x020000000002010B00410000001737D02101020081F1\x03'
2024-04-26 17:31:37.876 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737D, channel: 2, command: RELEASE, argument: 0, packet: b'\x020000000002010B00420000001737D0210102000071\x03'
2024-04-26 17:31:37.980 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737D, channel: 2, command: TRAIN, argument: 1, packet: b'\x020000000002010B00430000001737D02101020081EF\x03'
2024-04-26 17:31:41.012 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2024-04-26 17:31:41.012 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2024-04-26 17:31:41.025 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737D, channel: 2, command: TRAIN, argument: 1, packet: b'\x020000000002010B00440000001737D02101020081EE\x03'
2024-04-26 17:31:41.132 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737D, channel: 2, command: RELEASE, argument: 0, packet: b'\x020000000002010B00450000001737D021010200006E\x03'
2024-04-26 17:31:41.236 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737D, channel: 2, command: TRAIN, argument: 1, packet: b'\x020000000002010B00460000001737D02101020081EC\x03'

**Comment by dunimaniac** [comment]
> Hello, if you push a button on your Becker remote, is this visible in your log too? Just try to push stop or up

Nope its not tracked. Try to Pair the Stick with Becker CC41 and it works. But not in HA

**Comment by weidianer** [comment]
OK, you are saying you have a Becker CentralControl where you Centronic Stick V2 is able to pair. But in you HA the stick is not tracking your remote button pushed and cannot pair. But with CC41 everything works well. Correct?

What date can you see below the CE sign on the back of your Stick?

**Comment by dunimaniac** [comment]
> OK, you are saying you have a Becker CentralControl where you Centronic Stick V2 is able to pair. But in you HA the stick is not tracking your remote button pushed and cannot pair. But with CC41 everything works well. Correct?
> 
> What date can you see below the CE sign on the back of your Stick?
> 

23-22

**Comment by weidianer** [comment]
Ok, thanks seems the new sticks are kind of protected against third party usage. These are working sometimes for a short period of time and stop working immediately. Same with these 2 - same date range.

**Comment by weidianer** [comment]
![image](https://github.com/RainerStaude/hass-becker-component-plus-pybecker/assets/123209538/bb664605-de4c-46c8-89f4-55c466dbe921)

**Comment by dunimaniac** [comment]
I Think it stoped working after Updating HA or Becker Integration.

**Comment by weidianer** [comment]
I tried with old versions HA from 2023 and former Becker add-on. And also current versions- always the same, with the new centronic V2 sticks. It can work for a short period of time and than stops. I even tested native HA and also docker based installations- no difference.

**Comment by RainerStaude** [comment]
Unfortunately there are issues with the newer USB Sticks from 2023 onwards. As I don't have the failing USB Sick nor have any CC41 setup as reference, it is difficult to solve this issue.

**Comment by dunimaniac** [comment]
> don't

Hello Rainer. I can send you my Stick for research. Cheers

**Comment by RainerStaude** [comment]
> 
> 
> Hello Rainer. I can send you my Stick and the cc41 for research. Cheers

Maybe that would help. But I cannot promise on any timing. Could you please send me PM on LinkedIn (see GitHub profile)

**Comment by dunimaniac** [comment]
Hello Rainer, I have exchanged my stick for a new one. I was able to teach it to the motors without any problems and it works with the current HA version and the latest Becker version. Regardless of this, I can provide the CC41.

**Comment by Bias84** [comment]
> dunimaniac

Hello dunimaniac. Same problems here.
Could you please tell me, which version and date your new stick is?

Mine is 23-36

But I don't get a "Clack" on pushing the pairing-button on the becker remote control...

**Comment by MiSebCo** [comment]
I had a very similar issue. Solution was to unplug the stick, plug it back in and then reboot Home Assistant. Note: I have the stick plugged into a powered USB hub. Only rebooting Home Assistant without power cycling the stick did not change anything.
