### ISSUE TITLE
black 4035 200 041 0 not working

### ISSUE THREAD

**Issue by ch90045** [RainerStaude/hass-becker-component-plus-pybecker#41]
I purchased a black 4035 200 041 0 and that one shows up as /dev/serial/by-id/usb-Becker-Antriebe_GmbH_CDC_RS232_v125_Centronic-if00 which does differ from /dev/serial/by-id/usb-BECKER-ANTRIEBE_GmbH_CDC_RS232_v125_Centronic-if00 as the one you mentioned only has upper cases in ANTRIEBE.

I configured it via:
cover:

```
platform: becker
device: "/dev/serial/by-id/usb-Becker-Antriebe_GmbH_CDC_RS232_v125_Centronic-if00"
filename: "my-centronic-stick.db"
covers:
```
but i am lost afterwards - may that be a stick issue?

also i did see following:

`2024-06-12 14:38:18.185 DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737B, channel: 1, command: TRAIN, argument: 1, packet: b'\x020000000002010B00190000001737B021010100813A\x03'
2024-06-12 14:38:18.182 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: attempt to write a readonly database
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/becker/rf_device.py", line 73, in handle_pair
    await cls.becker.pair(f"{unit}:{channel}")
  File "/config/custom_components/becker/pybecker/becker.py", line 236, in pair
    await self.send(channel, "TRAIN")
  File "/config/custom_components/becker/pybecker/becker.py", line 178, in send
    await self.run_codes(ch, unit, cmd, test)
  File "/config/custom_components/becker/pybecker/becker.py", line 164, in run_codes
    self.db.set_unit(unit, test)
  File "/config/custom_components/becker/pybecker/database.py", line 141, in set_unit
    c.execute('UPDATE unit SET increment = ?, configured = ?, executed = ? WHERE code = ?',
sqlite3.OperationalError: attempt to write a readonly database`

**Comment by RainerStaude** [comment]
I guess this is meanwhile closed?
